#!/usr/bin/env node
// Merges data/quizzes/{st,scg,metaphysics}/*.json into app/data-quizzes.js
// Usage: node scripts/build-quizzes.cjs

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const QUIZ_DIR = path.join(ROOT, 'data', 'quizzes');
const OUT_FILE = path.join(ROOT, 'app', 'data-quizzes.js');

function loadDir(dirName) {
  const dir = path.join(QUIZ_DIR, dirName);
  const merged = {};
  if (!fs.existsSync(dir)) return merged;
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.json')).sort();
  for (const file of files) {
    const filePath = path.join(dir, file);
    let data;
    try {
      data = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    } catch (err) {
      console.error(`Error parsing ${filePath}: ${err.message}`);
      process.exit(1);
    }
    for (const key of Object.keys(data)) {
      if (merged[key]) {
        console.warn(`Warning: duplicate quiz key "${key}" found in ${file} (overwriting)`);
      }
      merged[key] = data[key];
    }
  }
  return merged;
}

const st = loadDir('st');
const scg = loadDir('scg');
const metaphysics = loadDir('metaphysics');

const stCount = Object.keys(st).length;
const scgCount = Object.keys(scg).length;
const metaCount = Object.keys(metaphysics).length;

const output = `// Auto-generated by scripts/build-quizzes.cjs — do not edit by hand.
// Rebuild any time with: node scripts/build-quizzes.cjs
window.QUIZZES = {
  st: ${JSON.stringify(st, null, 2)},
  scg: ${JSON.stringify(scg, null, 2)},
  metaphysics: ${JSON.stringify(metaphysics, null, 2)}
};
`;

fs.writeFileSync(OUT_FILE, output);
console.log(`Wrote ${OUT_FILE}`);
console.log(`  ST questions with quizzes: ${stCount}`);
console.log(`  SCG chapters with quizzes: ${scgCount}`);
console.log(`  Metaphysics chapters with quizzes: ${metaCount}`);
