// Compiles data/topics.json (the curated "Topics" cross-reference — objections/questions
// raised against Christianity/Catholicism by various traditions, mapped to the specific
// ST/SCG passages where Aquinas addresses them) into app/data-topics.js for the reader app.
//
// Each topic in topics.json carries `references` pointing into the ST/SCG text already
// loaded by app/data.js and app/data-scg.js; this script does not touch the scraped text
// itself, it only groups and reshapes topics.json into a form convenient to render as a
// collapsible-by-category list of linkable entries, mirroring the drawer's tree pattern.
//
// Usage: node build-topics.cjs

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const IN_FILE = path.join(ROOT, 'data', 'topics.json');
const OUT_FILE = path.join(ROOT, 'app', 'data-topics.js');

const CATEGORY_LABELS = {
  'atheist': 'Atheist & Skeptic Objections',
  'muslim': 'Islamic Theology',
  'jewish': 'Jewish Theology',
  'hindu': 'Hindu & Pantheist Perspectives',
  'non-catholic-christian': 'Non-Catholic Christian Disputes',
  'philosophical-foundations': 'Philosophical Foundations',
};

// Display order for categories in the drawer (unlisted categories are appended alphabetically).
const CATEGORY_ORDER = [
  'atheist',
  'muslim',
  'jewish',
  'hindu',
  'non-catholic-christian',
  'philosophical-foundations',
];

// Build a short human-readable location label + the app's own hash for a single reference,
// e.g. { label: "ST I, Q2, A3", hash: "P1Q2A3" } or { label: "SCG III, Ch. 71", hash: "SCG-B3C71" }.
const PART_ROMAN = { 1: 'I', 2: 'I-II', 3: 'II-II', 4: 'III' };
const BOOK_ROMAN = { 1: 'I', 2: 'II', 3: 'III', 4: 'IV' };

function describeReference(ref) {
  if (ref.work === 'ST') {
    var label = 'ST ' + (PART_ROMAN[ref.part] || ref.part) + ', Q' + ref.question +
      (ref.article != null ? ', A' + ref.article : '');
    var hash = 'P' + ref.part + 'Q' + ref.question + (ref.article != null ? 'A' + ref.article : '');
    return { work: 'ST', label: label, hash: hash, part: ref.part, question: ref.question, article: ref.article };
  }
  if (ref.work === 'SCG') {
    var label2 = 'SCG ' + (BOOK_ROMAN[ref.book] || ref.book) + ', Ch. ' + ref.chapter;
    var hash2 = 'SCG-B' + ref.book + 'C' + ref.chapter;
    return { work: 'SCG', label: label2, hash: hash2, book: ref.book, chapter: ref.chapter };
  }
  if (ref.work === 'Metaphysics') {
    // Not yet wired into the reader (no app/data-metaphysics.js / no "META" work-type in
    // app.js yet). Carried through structurally so a future pass can add navigation for it
    // without needing to touch this build script or topics.json again.
    return { work: 'Metaphysics', label: 'Metaphysics, Bk ' + ref.book + ', Ch. ' + ref.chapter, hash: null, book: ref.book, chapter: ref.chapter };
  }
  throw new Error('Unknown reference work: ' + JSON.stringify(ref));
}

function main() {
  var raw = fs.readFileSync(IN_FILE, 'utf-8');
  var topics = JSON.parse(raw);

  if (!Array.isArray(topics) || !topics.length) {
    throw new Error('data/topics.json is empty or not an array');
  }

  var byCategory = {};
  topics.forEach(function (t) {
    if (!t.id || !t.category || !t.question || !t.summary || !Array.isArray(t.references) || !t.references.length) {
      throw new Error('Malformed topic entry: ' + JSON.stringify(t));
    }
    var refs = t.references.map(describeReference);
    var entry = { id: t.id, question: t.question, summary: t.summary, references: refs };
    (byCategory[t.category] = byCategory[t.category] || []).push(entry);
  });

  var categoryKeys = Object.keys(byCategory).sort(function (a, b) {
    var ia = CATEGORY_ORDER.indexOf(a), ib = CATEGORY_ORDER.indexOf(b);
    if (ia === -1) ia = CATEGORY_ORDER.length + a.localeCompare(b);
    if (ib === -1) ib = CATEGORY_ORDER.length + b.localeCompare(b);
    return ia - ib;
  });

  var categories = categoryKeys.map(function (key) {
    return {
      key: key,
      label: CATEGORY_LABELS[key] || key,
      topics: byCategory[key],
    };
  });

  var totalTopics = topics.length;
  var totalRefs = topics.reduce(function (sum, t) { return sum + t.references.length; }, 0);

  var out = '// Generated by scripts/build-topics.cjs from data/topics.json. Do not edit by hand.\n' +
    '// ' + totalTopics + ' topics across ' + categories.length + ' categories, ' + totalRefs + ' total references.\n' +
    'window.TOPICS = ' + JSON.stringify({ categories: categories }, null, 2) + ';\n';

  fs.writeFileSync(OUT_FILE, out);
  console.log('Wrote ' + OUT_FILE + ' (' + totalTopics + ' topics, ' + categories.length + ' categories, ' + totalRefs + ' references)');
  categories.forEach(function (c) {
    console.log('  ' + c.key + ': ' + c.topics.length);
  });
}

main();
